#!/bin/bash

PLUGIN_DIR="$CONFIG_DIR/plugins"
ITEM_DIR="$CONFIG_DIR/items"
LABEL_FONT="SF Pro"
ICON_FONT="Hack Nerd Font"

sketchybar --bar position=top height=35 blur_radius=0 color=0000000000

default=(
  padding_left=5
  padding_right=5
  icon.font="$ICON_FONT:Bold:13.0"
  label.font="$LABEL_FONT:Semibold:13.0"
  icon.color=0xffffffff
  label.color=0xffffffff
  icon.padding_left=4
  icon.padding_right=4
  label.padding_left=4
  label.padding_right=4
  updates=on
)
sketchybar --default "${default[@]}"

#### Left Side
source "$ITEM_DIR/apple_logo.sh" # Apple logo
source "$ITEM_DIR/open_app.sh" # Open App
source "$ITEM_DIR/aerospace.sh" # Aerospace Buttons

#### Notch

#### Right Side
source "$ITEM_DIR/clock.sh" # Clock
source "$ITEM_DIR/wifi.sh" # Wifi

source "$ITEM_DIR/battery.sh" # Battery
source "$ITEM_DIR/control_center.sh" # Control Center
source "$ITEM_DIR/volume.sh" # Volume



##### Force all scripts to run the first time (never do this in a script) #####
sketchybar --update
